version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: kileorguy/laravel
    container_name: laravel
    restart: unless-stopped
    environment:
      - APP_ENV=local
    ports:
      - '1234:80'
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_USER_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network
    ports:
      - ${DB_HOST}:${DB_PORT}

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
